### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by exoego** [TanUkkii007/reactive-zookeeper#8]
It would be helpful if this library supports Scala 2.13.

**Comment by exoego** [comment]
It seems that this repository is no longer actively maintained.

We at chatwork forked this repository and published on Sonatype:
https://github.com/chatwork/reactive-zookeeper/releases/tag/1.0.0

Thanks for starting this project.

**Comment by TanUkkii007** [comment]
Thanks for the suggestion and I am very sorry for being inactive.
Thanks again for the fork!
