### ISSUE TITLE
Consider migration from Bintray

### ISSUE THREAD

**Issue by exoego** [TanUkkii007/reactive-zookeeper#9]
[Bintray is going to shut down on 2021/5/1](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

It seems that this artifact is currently published only on Bintray.
It would be helpful if this is published on other artifact repository, like Sonatype or GitHub.

**Comment by exoego** [comment]
It seems that this repository is no longer actively maintained.

We at chatwork forked this repository and published on Sonatype:
https://github.com/chatwork/reactive-zookeeper/releases/tag/1.0.0

Thanks for starting this project.

**Comment by TanUkkii007** [comment]
Thanks for the suggestion and I am very sorry for being inactive.
Thanks again for the fork!
